trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

variables:  # Define environment variables at the top level
  CLIENT_ID: eea00c11-1882-474b-b15b-68e2d3ff5b86
  CLIENT_SECRET: KQw8Q~0pp4V4_Kd3064Tf2qEqUQI77TAUZrRcbVu
  SUBSCRIPTION_ID: d67abf55-c27e-4ee6-90cd-ce276d7d04b7
  TENANT_ID: 445535a9-31f3-4c74-a04b-348d3e339d24

stages:
  - stage: Dev
    jobs:
      - job: Deploy_to_Dev
        displayName: 'Deploy Infrastructure to Dev'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to Dev'

  - stage: QA
    jobs:
      - job: Deploy_to_QA
        displayName: 'Deploy Infrastructure to QA'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd qa
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to QA'

  - stage: PreProd
    jobs:
      - job: Deploy_to_PreProd
        displayName: 'Deploy Infrastructure to Pre-Prod'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd preprod
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to Pre-Prod'

  - stage: Prod
    jobs:
      - job: Deploy_to_Prod
        displayName: 'Deploy Infrastructure to Prod'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd prod
              terraform init
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to Prod'
