trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

stages:
  - stage: Dev
    jobs:
      - job: Deploy_to_Dev
        displayName: 'Deploy Infrastructure to Dev'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              # Add steps to authenticate with Azure (e.g., using Azure CLI)
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              # Install Terraform
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              # Run Terraform commands
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to Dev'
        env:
          CLIENT_ID: $(CLIENT_ID)
          CLIENT_SECRET: $(CLIENT_SECRET)
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          TENANT_ID: $(TENANT_ID)

  - stage: QA
    jobs:
      - job: Deploy_to_QA
        displayName: 'Deploy Infrastructure to QA'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              # Add steps to authenticate with Azure (e.g., using Azure CLI)
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              # Install Terraform
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              # Run Terraform commands
              cd qa
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to QA'
        env:
          CLIENT_ID: $(CLIENT_ID)
          CLIENT_SECRET: $(CLIENT_SECRET)
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          TENANT_ID: $(TENANT_ID)

  - stage: PreProd
    jobs:
      - job: Deploy_to_PreProd
        displayName: 'Deploy Infrastructure to Pre-Prod'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              # Add steps to authenticate with Azure (e.g., using Azure CLI)
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              # Install Terraform
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              # Run Terraform commands
              cd preprod
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to Pre-Prod'
        env:
          CLIENT_ID: $(CLIENT_ID)
          CLIENT_SECRET: $(CLIENT_SECRET)
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          TENANT_ID: $(TENANT_ID)

  - stage: Prod
    jobs:
      - job: Deploy_to_Prod
        displayName: 'Deploy Infrastructure to Prod'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              # Add steps to authenticate with Azure (e.g., using Azure CLI)
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              # Install Terraform
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              # Run Terraform commands
              cd prod
              terraform init
              terraform apply -auto-approve tfplan
            displayName: 'Deploy to Prod'
        env:
          CLIENT_ID: $(CLIENT_ID)
          CLIENT_SECRET: $(CLIENT_SECRET)
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          TENANT_ID: $(TENANT_ID)

