trigger:
- main  # Adjust this to your main branch name

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install --upgrade pip
    pip install terraform
  displayName: 'Install Terraform'

- script: |
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'tfplan'
    publishLocation: 'pipeline'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: '<FirstPipeline'
    deploymentScope: 'Resource Group'
    deploymentScopeSelector: 'resourceGroupName'
    subscriptionId: '74f18b4b-73a2-49ee-a8b5-9e6f8c8ec835'
    resourceGroupName: 'Dev'
    terraformVersion: 'latest'
    commandOptions: '-auto-approve'
